/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "met": {
          dark: '#0B1120',
          card: '#111827',
          surface: '#1E293B',
          border: '#334155',
          text: '#F8FAFC',
          muted: '#94A3B8',
          accent: '#38BDF8',
          danger: '#EF4444',
          warning: '#F59E0B',
          success: '#10B981',
          bust: '#DC2626'
        },
        // Contributor Avi AETHER-CAST tokens
        "surface-container-high": "#262a33",
        "on-tertiary-fixed": "#410004",
        "on-surface": "#dfe2ee",
        "on-primary-fixed-variant": "#004f53",
        "error-container": "#93000a",
        "surface-tint": "#00dce6",
        "tertiary-fixed-dim": "#ffb3ae",
        "surface-bright": "#353942",
        "on-tertiary-fixed-variant": "#930014",
        "primary-fixed": "#6ff6ff",
        "secondary-fixed": "#f0dbff",
        "primary": "#e0fdff",
        "on-primary": "#00373a",
        "on-surface-variant": "#b9cacb",
        "inverse-on-surface": "#2c3039",
        "primary-container": "#00f2fe",
        "on-secondary-fixed-variant": "#6900b3",
        "surface-container-low": "#181c24",
        "inverse-primary": "#00696f",
        "on-tertiary-container": "#bc1925",
        "surface-container-highest": "#31353e",
        "tertiary-fixed": "#ffdad7",
        "surface": "#0f131c",
        "inverse-surface": "#dfe2ee",
        "tertiary": "#fff5f4",
        "on-background": "#dfe2ee",
        "on-tertiary": "#68000b",
        "tertiary-container": "#ffd0cc",
        "on-primary-fixed": "#002022",
        "on-primary-container": "#006a70",
        "on-secondary-container": "#d6a9ff",
        "surface-variant": "#31353e",
        "outline-variant": "#3a494b",
        "on-secondary-fixed": "#2c0051",
        "background": "#0f131c",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#00dce6",
        "surface-container-lowest": "#0a0e16",
        "surface-container": "#1c2028",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#ddb7ff",
        "surface-dim": "#0f131c",
        "secondary-container": "#6f00be",
        "on-secondary": "#490080",
        "outline": "#849495",
        "on-error": "#690005",
        "secondary": "#ddb7ff"
      },
      spacing: {
        "gutter": "0.75rem",
        "space-xs": "0.25rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "margin-desktop": "1.5rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "1rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "mono-metric": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "mono-display": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "label-badge": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
